# Generated by Django 5.1.7 on 2025-05-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
