# Generated by Django 5.1.7 on 2025-04-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0002_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
