# Generated by Django 5.1.7 on 2025-05-27 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0002_chatmessage_is_read'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='bem_chatmes_event_i_1bc014_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['event', 'created_at'], name='bem_chatmes_event_i_0d71ed_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['receiver', 'created_at'], name='bem_chatmes_receive_51caa4_idx'),
        ),
    ]
