# Generated by Django 5.1.6 on 2025-06-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0002_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='devicetoken',
            unique_together={('user', 'token')},
        ),
    ]
