# Generated by Django 5.1.6 on 2025-06-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0003_devicetoken'),
        ('bem', '0003_remove_chatmessage_bem_chatmes_event_i_1bc014_idx_and_more'),
    ]

    operations = [
    ]
