# Generated by Django 5.1.6 on 2025-06-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bem', '0003_alter_devicetoken_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['-discount_percentage', 'valid_to']},
        ),
    ]
